#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

NAMESPACE_DEVTRON="devtroncd"

DEVTRON_HELM_VERSION="0.22.53"

"$SNAP/microk8s-enable.wrapper" helm3
"$SNAP/microk8s-enable.wrapper" dns
"$SNAP/microk8s-enable.wrapper" storage

KUBECTL="$SNAP/microk8s-kubectl.wrapper"
HELM="$SNAP/microk8s-helm3.wrapper"

VALUES=""

# get the options
while getopts ":v:f:h:" flag; do
  case "${flag}" in
          v) DEVTRON_HELM_VERSION=${OPTARG}
             ;;
          f) VALUES=${OPTARG}
             ;;
          *) echo "Usage: microk8s enable devtron"
             echo ""
             echo "With overwriting default values: microk8s enable devtron -f values.yaml"
             echo ""
             echo "See https://artifacthub.io/packages/helm/devtron/devtron-operator for more information about the values"
             echo "You should enable the Ingress addon, if you want to use Devtron with an Ingress"
             echo "To enable the Ingress addon run --- microk8s enable ingress"
             exit 0
             ;;
  esac
done

echo "Installing Devtron through Helm (Helm v${DEVTRON_HELM_VERSION})"

if [ -n "$VALUES" ]; then
    echo "Using values file: $VALUES"
fi


# make sure the "devtroncd" namespace exists
$KUBECTL create namespace "$NAMESPACE_DEVTRON" > /dev/null 2>&1 || true

# add the Devtron chart repository
$HELM repo add devtron https://helm.devtron.ai

# install the helm chart
if [ -z "$VALUES" ]
then
    $HELM upgrade --install devtron devtron/devtron-operator \
      --version $DEVTRON_HELM_VERSION \
      --namespace "$NAMESPACE_DEVTRON" \
      --set installer.arch=multi-arch
else
    $HELM upgrade --install devtron devtron/devtron-operator \
      --version $DEVTRON_HELM_VERSION \
      --namespace "$NAMESPACE_DEVTRON" \
      --set installer.arch=multi-arch \
      -f $VALUES
fi

echo "Devtron is installed"
